### ISSUE TITLE
Missing ting.http.Middleware

### ISSUE THREAD

**Issue by Grabli66** [haxetink/tink_websocket#1]

**Comment by kevinresol** [comment]
what do you mean?

**Comment by Grabli66** [comment]
https://github.com/haxetink/tink_websocket/blob/1f7df103faec28634ce5e4a899c1c67a9c15ef79/src/tink/http/middleware/WebSocket.hx#L5

But tink_http does not have type Middleware

This class was removed by this commit
https://github.com/haxetink/tink_http/commit/f40e3021caf4a7628b152657da1867dc93c61f1c

I tried to find out where is this class now, but i could not.

**Comment by kevinresol** [comment]
It is here https://github.com/kevinresol/tink_http_middleware

**Comment by Grabli66** [comment]
Maybe it's better to place that library to haxetink?

**Comment by kevinresol** [comment]
@back2dos what do you think?

**Comment by back2dos** [comment]
Yeah, sure, why not ;)

**Comment by Grabli66** [comment]
Thanks.
