### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by Grabli66** [haxetink/tink_websocket#3]
Library tink_tcp does not have such types:
1. tink.tcp.nodejs.NodejsConnector
https://github.com/haxetink/tink_websocket/blob/1f7df103faec28634ce5e4a899c1c67a9c15ef79/src/tink/websocket/clients/TcpClient.hx#L38
2. tink.tcp.Handler
https://github.com/haxetink/tink_websocket/blob/1f7df103faec28634ce5e4a899c1c67a9c15ef79/src/tink/websocket/Connector.hx#L14

**Comment by kevinresol** [comment]
Please use pure branch of tink_tcp

**Comment by Grabli66** [comment]
Ok

**Comment by kevinresol** [comment]
Let this remind me to merge that branch
